### ISSUE TITLE
arrayIntersection is not equal intersection?

### ISSUE THREAD

**Issue by wszgrcy** [aanckar/interval-operations#11]
```ts
    console.log(arrayIntersection([[1, 2]], [[2, 3]]))  // === []
    console.log(intersection([1, 2], [2, 3]))  // === [ 2, 2 ]
```
if Interval design is [x,y) I think `arrayIntersection` is right.
then I try `union` ,It is indeed [x,y) ,so `intersection` return error?

**Comment by aanckar** [comment]
Thanks for noticing this. I just published `2.0.0` which now uses open intervals when intersecting (something like `[2, 2]` isn't very useful for my use cases at least).
